/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/morgan-plus-four-d884f2b5720a4fce918f461f6ff2fa2e
Title: Morgan Plus Four
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = (props) => {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.274, 0]} rotation={[0, 0, 0.622]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.car_body_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.car_body_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.external_accessories_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.big_interior_details_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.small_interior_details_mat}
        />
        <group rotation={[0, 0, -0.622]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.bottom_details_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.wheels_and_bottom_details_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.external_accessories_mat}
          />
        </group>
        <group rotation={[0, 0, 0.595]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.small_interior_details_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.panel_data_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.big_interior_details_mat}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.glass_mat}
          rotation={[0, 0, 0.782]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.display_mat}
          rotation={[0, 0, 0.595]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.wheels_and_bottom_details_mat}
          rotation={[0, 0, -0.622]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.wheels_and_bottom_details_mat}
          rotation={[0, 0, -0.622]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
export default Model;